default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: your_port
  username: your_username
  password: your_password
  host: your_host

development:
  <<: *default
  database: message_api_development

test:
  <<: *default
  database: message_api_test

production:
  <<: *default
  database: message_api_production
  username: message_api
  password: <%= ENV["MESSAGE_API_DATABASE_PASSWORD"] %>
